import os
from xml.etree import ElementTree
from xml.dom import minidom
from xml.etree.ElementTree import Element, SubElement, Comment
import numpy as np

from sumeval.metrics.rouge import RougeCalculator
from nltk.translate.bleu_score import sentence_bleu

from nltk.translate.bleu_score import SmoothingFunction
smoothie = SmoothingFunction().method4


from nltk.translate.bleu_score import SmoothingFunction
smoothie = SmoothingFunction().method4

def eval(
    reference_summary, model_summary, metrics=["ROUGE_1", "ROUGE_2", "ROUGE_L", "NUBIA", "BLEURT"]):

    rouge = RougeCalculator(stopwords=True, lang="en")

    if("ROUGE_1" in metrics):
      rouge_1 = rouge.rouge_n( summary=model_summary, references=reference_summary, n=1)

    else:
      rouge_1 = None

    if("ROUGE_2" in metrics):
      rouge_2 = rouge.rouge_n(summary=model_summary,references=[reference_summary],n=2)
    else:
      rouge_2 = None

    if("ROUGE_L" in metrics):
      rouge_l = rouge.rouge_l( summary=model_summary,references=[reference_summary])
    else:
      rouge_l = None
      
    if("BLEU" in metrics):
      try:
          bleu = 0#sentence_bleu( reference_summary.split(" "), model_summary.split(" "), smoothing_function=smoothie)
      except:
          bleu = 0
    else:
      bleu = None
    return rouge_1, rouge_2,rouge_l, bleu

def prettify(elem):
      """Return a pretty-printed XML string for the Element.
      """
      rough_string = ElementTree.tostring(elem, 'utf-8')
      reparsed = minidom.parseString(rough_string)
      return reparsed.toprettyxml(indent="  ")
  
def create_report_valid(
    summary_array, references_summary, article, name_file,
     metrics=["ROUGE_1", "ROUGE_2", "ROUGE_L", "NUBIA", "BLEURT"]):

  rouge_1_arr  = []
  rouge_2_arr  = []
  rouge_L_arr  = []
  bleu_arr = []

  top = Element('ZakSum')

  comment = Comment('Generated by Amr Zaki')
  top.append(comment)

  i=0
  for summ in summary_array:

    if i % 1000 == 0:
        print(i)
      
    example = SubElement(top, 'example')
    article_element   = SubElement(example, 'article')
    article_element.text = article[i]
  
    reference_element = SubElement(example, 'reference')
    reference_element.text = references_summary[i]
  
    summary_element   = SubElement(example, 'summary')
    summary_element.text = summ

    if(len(summ) != 0):
      rouge_1, rouge_2, rouge_L, bleu = eval(references_summary[i],summ, metrics=metrics )
    else: 
      rouge_1 = rouge_2 = rouge_L = 0

    if(rouge_1 != None):
      rouge_1_arr.append(rouge_1) 
    if(rouge_2 != None):
      rouge_2_arr.append(rouge_2)
    if(rouge_L != None):
      rouge_L_arr.append(rouge_L)
    if(bleu != None):
      bleu_arr.append(bleu)

    i+=1

    eval_element = SubElement(example, 'eval')
    ROUGE_1_element  = SubElement(eval_element, 'ROUGE_1' , {'score':str(rouge_1)})
    ROUGE_2_element  = SubElement(eval_element, 'ROUGE_2' , {'score':str(rouge_2)})
    ROUGE_L_element  = SubElement(eval_element, 'ROUGE_l' , {'score':str(rouge_L)})
    BLEU_element  = SubElement(eval_element, 'BLEU' , {'score':str(bleu_arr)})

  if(rouge_1_arr != []): top.set('rouge_1', str(np.mean(rouge_1_arr)))
  if(rouge_2_arr != []): top.set('rouge_2', str(np.mean(rouge_2_arr)))
  if(rouge_L_arr != []): top.set('rouge_L', str(np.mean(rouge_L_arr)))
  if(bleu_arr != []): top.set('BLEU', str(np.mean(bleu_arr)))


  with open(name_file, "w+") as f:
    print(prettify(top), file=f)